export const ADD_EDITING_COLOR_TOKEN_MODIFICATION =
  "colorTokenModifications/edit/ADD_COLOR_TOKEN_MODIFICATION";

export const UPDATE_EDITING_COLOR_TOKEN_MODIFICATION =
  "colorTokenModifications/edit/UPDATE_COLOR_TOKEN_MODIFICATION";

export const REMOVE_EDITING_COLOR_TOKEN_MODIFICATION =
  "colorTokenModifications/edit/REMOVE_COLOR_TOKEN_MODIFICATION";
